spring.datasource.url=jdbc:postgresql://GkdRGe4qRd2omXlnZ1SBp7Ul83AvbSKB@dpg-csohmbe8ii6s7395o2dg-a.oregon-postgres.render.com/todo_application_uqb3
spring.datasource.username=todo_application_uqb3_user
spring.datasource.password=GkdRGe4qRd2omXlnZ1SBp7Ul83AvbSKB
spring.jpa.hibernate.ddl-auto=update
spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_ENUMS=true
sentry.dsn=https://badc9792061c2600b7f6bcc4f1d3dea6@o4506149321637888.ingest.sentry.io/4506152902787072
sentry.traces-sample-rate=1.0
sentry.exception-resolver-order=-2147483647
logging.level.org.springframework=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=todoapplication876@gmail.com
spring.mail.password=irkf rdjh qiiy pjcb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
development.cross.origin="http://localhost:8080"
